version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.Server
      args:
        DATABASE_URL: ${DATABASE_URL}
        CORS_ORIGIN: ${CORS_ORIGIN}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}

  analyzer:
    build:
      context: .
      dockerfile: Dockerfile.Analyzer
      args:
        DATABASE_URL: ${DATABASE_URL}
        CORS_ORIGIN: ${CORS_ORIGIN}
        REACT_APP_ANALYZER_API_BASE_URL: ${REACT_APP_ANALYZER_API_BASE_URL}
    ports:
      - "3002:3002"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}

  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile.Frontend
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
        REACT_APP_GOOGLE_CLIENT_ID: ${REACT_APP_GOOGLE_CLIENT_ID}
        REACT_APP_ANALYZER_API_BASE_URL: ${REACT_APP_ANALYZER_API_BASE_URL}
    ports:
      - "3000:80"
    env_file:
      - .env
