version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.Server
      args:
        DATABASE_URL: ${DATABASE_URL}
        CORS_ORIGIN: ${CORS_ORIGIN}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    ports:
      - "3001:3001"
    env_file:
      - .env

  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile.Frontend
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
        REACT_APP_GOOGLE_CLIENT_ID: ${REACT_APP_GOOGLE_CLIENT_ID}
    ports:
      - "3000:80"
    env_file:
      - .env
