name: Build, Push, and Update GitLab

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REACT_APP_API_BASE_URL: ${{ vars.REACT_APP_API_BASE_URL }}
  REACT_APP_ANALYZER_API_BASE_URL: ${{ vars.REACT_APP_ANALYZER_API_BASE_URL }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
  CORS_ORIGIN: ${{ vars.CORS_ORIGIN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  REACT_APP_DATABASE_URL: ${{ secrets.REACT_APP_DATABASE_URL }}
  GITLAB_DEPLOY_KEY: ${{ secrets.GITLAB_DEPLOY_KEY }}
  OPEN_API_KEY: ${{ secrets.OPEN_API_KEY}}
  COLLECTOR_DATABASE_URL: ${{ secrets.COLLECTOR_DATABASE_URL}}

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: npm

      # - name: Install backend dependencies and run tests
      #   run: |
      #     cd server
      #     npm ci
      #     npm test

      # - name: Install frontend dependencies and run tests
      #   run: |
      #     cd react
      #     npm ci
      #     npm test

      - name: Install analyzer dependencies and run tests
        run: |
          rm -rf node_modules package-lock.json
          npm install
          npm test

      - name: Install collector dependencies and run tests
        run: |
          cd collector
          rm -rf node_modules package-lock.json
          npm install
          npm test

  build-backend:
    runs-on: ubuntu-latest
    needs: run-all-tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: npm

      - name: Install backend dependencies
        run: npm ci

      - name: Build backend
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate backend version
        id: backend-version
        run: |
          BACKEND_VERSION="v$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
          echo "BACKEND_VERSION=$BACKEND_VERSION" >> $GITHUB_ENV

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.Server
          push: true
          tags: davi1493/quiz-app-backend:${{ env.BACKEND_VERSION }}
          build-args: |
            GOOGLE_CLIENT_ID=${{ env.GOOGLE_CLIENT_ID }}
            CORS_ORIGIN=${{ env.CORS_ORIGIN }}
            DATABASE_URL=${{ env.DATABASE_URL }}

      - name: Set up SSH for GitLab
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.GITLAB_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts

      - name: Clone GitLab repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone --depth=1 git@gitlab.com:cu-group/quiz-proj.git gitlab-repo

      - name: Update backend image tag
        run: |
          cd gitlab-repo/manifests
          sed -i "s|image: .*quiz-app-backend:.*|image: docker.io/davi1493/quiz-app-backend:${{ env.BACKEND_VERSION }}|" backend-deployment.yaml

      - name: Commit and push backend update
        run: |
          cd gitlab-repo
          git add manifests/backend-deployment.yaml
          git commit -m "chore: update backend image tag to ${{ env.BACKEND_VERSION }}"
          git push origin main

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate frontend version
        id: frontend-version
        run: |
          FRONTEND_VERSION="v$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
          echo "FRONTEND_VERSION=$FRONTEND_VERSION" >> $GITHUB_ENV

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./react
          file: ./react/Dockerfile.Frontend
          push: true
          tags: davi1493/quiz-app-frontend:${{ env.FRONTEND_VERSION }}
          build-args: |
            REACT_APP_API_BASE_URL=${{ env.REACT_APP_API_BASE_URL }}
            REACT_APP_GOOGLE_CLIENT_ID=${{ env.REACT_APP_GOOGLE_CLIENT_ID }}
            REACT_APP_ANALYZER_API_BASE_URL=${{ env.REACT_APP_ANALYZER_API_BASE_URL}}

      - name: Set up SSH for GitLab
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.GITLAB_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts

      - name: Clone GitLab repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone --depth=1 git@gitlab.com:cu-group/quiz-proj.git gitlab-repo

      - name: Update frontend image tag
        run: |
          cd gitlab-repo/manifests
          sed -i "s|image: .*quiz-app-frontend:.*|image: docker.io/davi1493/quiz-app-frontend:${{ env.FRONTEND_VERSION }}|" frontend-deployment.yaml

      - name: Commit and push frontend update
        run: |
          cd gitlab-repo
          git add manifests/frontend-deployment.yaml
          git commit -m "chore: update frontend image tag to ${{ env.FRONTEND_VERSION }}"
          git push origin main

  build-analyzer:
    runs-on: ubuntu-latest
    needs:
      - build-frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate analyzer version
        id: analyzer-version
        run: |
          ANALYZER_VERSION="v$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
          echo "ANALYZER_VERSION=$ANALYZER_VERSION" >> $GITHUB_ENV

      - name: Build and push analyzer image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.Analyzer
          push: true
          tags: davi1493/quiz-app-analyzer:${{ env.ANALYZER_VERSION }}
          build-args: |
            DATABASE_URL=${{ env.DATABASE_URL }}
            CORS_ORIGIN=${{ env.CORS_ORIGIN }}
            REACT_APP_ANALYZER_API_BASE_URL=${{ env.REACT_APP_ANALYZER_API_BASE_URL }}

      - name: Set up SSH for GitLab
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.GITLAB_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts

      - name: Clone GitLab repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone --depth=1 git@gitlab.com:cu-group/quiz-proj.git gitlab-repo

      - name: Update analyzer image tag
        run: |
          cd gitlab-repo/manifests
          sed -i "s|image: .*quiz-app-analyzer:.*|image: docker.io/davi1493/quiz-app-analyzer:${{ env.ANALYZER_VERSION }}|" analyzer-deployment.yaml

      - name: Commit and push analyzer update
        run: |
          cd gitlab-repo
          git add manifests/analyzer-deployment.yaml
          git commit -m "chore: update analyzer image tag to ${{ env.ANALYZER_VERSION }}"
          git push origin main

  build-collector:
    runs-on: ubuntu-latest
    needs:
      - build-analyzer
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate collector version
        id: collector-version
        run: |
          COLLECTOR_VERSION="v$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
          echo "COLLECTOR_VERSION=$COLLECTOR_VERSION" >> $GITHUB_ENV

      - name: Build and push collector image
        uses: docker/build-push-action@v6
        with:
          context: ./collector
          file: ./collector/Dockerfile
          push: true
          tags: davi1493/quiz-collector-app:${{ env.COLLECTOR_VERSION }}
          build-args: |
            COLLECTOR_DATABASE_URL=${{ env.COLLECTOR_DATABASE_URL }}
            OPEN_API_KEY=${{ env.OPEN_API_KEY }}

      - name: Set up SSH for GitLab
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.GITLAB_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts

      - name: Clone GitLab repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone --depth=1 git@gitlab.com:cu-group/quiz-proj.git gitlab-repo

      - name: Update collector image tag
        run: |
          cd gitlab-repo/manifests
          sed -i "s|image: .*quiz-collector-app:.*|image: docker.io/davi1493/quiz-collector-app:${{ env.COLLECTOR_VERSION }}|" collector-deployment.yaml

      - name: Commit and push collector update
        run: |
          cd gitlab-repo
          git add manifests/collector-deployment.yaml
          git commit -m "chore: update collector image tag to ${{ env.COLLECTOR_VERSION }}"
          git push origin main
