name: Build and Push

on: push

jobs:
  dockerPush:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate dynamic version
        id: version
        run: |
          VERSION="v$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push with Buildx
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: davi1493/quiz-app:${{ env.VERSION }}

      - name: Set up SSH for GitLab
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

      - name: Clone GitLab repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone git@gitlab.com:cu-group/quiz-proj.git gitlab-repo

      - name: Update image tag in deployment
        run: |
          cd gitlab-repo/manifests
          sed -i "s|image: docker.io/davi1493/quiz-app:.*|image: docker.io/davi1493/quiz-app:${{ env.VERSION }}|" server-deployment.yaml

      - name: Commit and push updated image tag
        run: |
          cd gitlab-repo
          git add manifests/server-deployment.yaml
          git commit -m "chore: update image tag to ${{ env.VERSION }}"
          git push origin main
