name: Build, Push, and Update GitLab

on: push

env:
  REACT_APP_API_BASE_URL: ${{ vars.REACT_APP_API_BASE_URL }}
  GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID }}
  REACT_APP_GOOGLE_CLIENT_ID: ${{ vars.REACT_APP_GOOGLE_CLIENT_ID }}
  CORS_ORIGIN: ${{ vars.CORS_ORIGIN }}

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: npm

      - name: Install backend dependencies
        run: npm ci

      - name: Build backend
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate backend version
        id: backend-version
        run: |
          BACKEND_VERSION="v$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
          echo "BACKEND_VERSION=$BACKEND_VERSION" >> $GITHUB_ENV

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.Server
          push: true
          tags: davi1493/quiz-app-backend:${{ env.BACKEND_VERSION }}
          build-args: |
            REACT_APP_API_BASE_URL=${{ env.REACT_APP_API_BASE_URL }}
            GOOGLE_CLIENT_ID=${{ env.GOOGLE_CLIENT_ID }}
            REACT_APP_GOOGLE_CLIENT_ID=${{ env.RECT_APP_GOOGLE_CLIENT_ID }}
            CORS_ORIGIN=${{ env.CORS_ORIGIN }}

      - name: Set up SSH for GitLab
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts

      - name: Clone GitLab repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone --depth=1 git@gitlab.com:cu-group/quiz-proj.git gitlab-repo

      - name: Update backend image tag
        run: |
          cd gitlab-repo/manifests
          sed -i "s|image: .*quiz-app-backend:.*|image: docker.io/davi1493/quiz-app-backend:${{ env.BACKEND_VERSION }}|" backend-deployment.yaml

      - name: Commit and push backend update
        run: |
          cd gitlab-repo
          git add manifests/backend-deployment.yaml
          git commit -m "chore: update backend image tag to ${{ env.BACKEND_VERSION }}"
          git push origin main

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate frontend version
        id: frontend-version
        run: |
          FRONTEND_VERSION="v$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
          echo "FRONTEND_VERSION=$FRONTEND_VERSION" >> $GITHUB_ENV

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./react
          file: ./react/Dockerfile.Frontend
          push: true
          tags: davi1493/quiz-app-frontend:${{ env.FRONTEND_VERSION }}
          build-args: |
            REACT_APP_API_BASE_URL=${{ env.REACT_APP_API_BASE_URL }}
            GOOGLE_CLIENT_ID=${{ env.GOOGLE_CLIENT_ID }}
            REACT_APP_GOOGLE_CLIENT_ID=${{ env.RECT_APP_GOOGLE_CLIENT_ID }}
            CORS_ORIGIN=${{ env.CORS_ORIGIN }}

      - name: Set up SSH for GitLab
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts

      - name: Clone GitLab repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone --depth=1 git@gitlab.com:cu-group/quiz-proj.git gitlab-repo

      - name: Update frontend image tag
        run: |
          cd gitlab-repo/manifests
          sed -i "s|image: .*quiz-app-frontend:.*|image: docker.io/davi1493/quiz-app-frontend:${{ env.FRONTEND_VERSION }}|" frontend-deployment.yaml

      - name: Commit and push frontend update
        run: |
          cd gitlab-repo
          git add manifests/frontend-deployment.yaml
          git commit -m "chore: update frontend image tag to ${{ env.FRONTEND_VERSION }}"
          git push origin main
